[package]
name = "riemann-core"
version = "0.1.0"
authors = ["James Prestwich <james@prestwi.ch>"]
edition = "2018"
description = "Abstract UTXO transactions to enable code reuse across chains"
repository = "https://github.com/summa-tx/riemann-rs"
license = "LGPL-3.0-or-later"

[dependencies]
bitcoin-spv = "2.0.0"
hex = "0.4.2"
thiserror = "1.0"
sha2 = "0.8.0"
