[package]
name = "rmn-bip32"
version = "0.1.0-beta.0"
authors = ["James Prestwich <james@prestwi.ch>"]
edition = "2018"
description = "Bip32 (and related BIPs) in Rust"
repository = "https://github.com/summa-tx/riemann-rs"
license = "LGPL-3.0-or-later"

[dependencies]
secp256k1 = { version = "0.17.2", features = ["recovery"], optional = true }
thiserror = "1.0"
hmac = "0.7.1"
sha2 = "0.8.0"
bitcoin-spv = "2.0.0"
bs58 = "0.3.0"
lazy_static = "1.4.0"
riemann-core = { path = "../core"}

[dependencies.libsecp256k1]
git = "https://github.com/paritytech/libsecp256k1.git"
default-features = false
optional = true
features = ["std", "hmac"]

[dependencies.libsecp256k1-core]
git = "https://github.com/paritytech/libsecp256k1.git"
default-features = false
optional = true
features = ["std"]

[dev-dependencies]
hex = "0.4.2"
criterion = "0.3.1"

[features]
default = ["libsecp"]
rust-secp-static-context = ["libsecp256k1/static-context"]
libsecp = ["secp256k1"]
rust-secp = ["libsecp256k1", "libsecp256k1-core"]

[[bench]]
name = "bench"
harness = false
